require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/salemove/glia-ios-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target 'GliaWidgetsModuleExample' do


  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-glia-widgets-module', :path => '../..'

  pod 'SalemoveSDK'

  use_frameworks!
#  pod 'GliaWidgets'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper' => '0.80.0' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end
