# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

source 'https://github.com/salemove/glia-ios-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'GliaWidgetsModule' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # pod 'GliaWidgets', git: 'https://github.com/salemove/ios-sdk-widgets', tag: '0.5.2'

end
